/*

	C Fundamentals: Labo YT5883
	Exercices from "Cprogrammingfundamentals2020"

	Name: Celik
	Firstname:Ennis
	Class: 1EICT

*/


#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <time.h>
#include <math.h>
#include <string.h>

/* Some Parameteres */

#define Days 7 // This parameter is to stay at the value '7' since we only have 7 days of the week. Exceeding this number will result in errors!!!
#define Day_NameLength 5 // This parameter is to stay at the value '5'. Exceeding this number will result in "buffer overrun" and "printing" errors!!!
#define Number_of_Temperatures 10 // This is a parameter that can be changed in order to have temperature results beyond 1 week.

// These parameters determine the maximum and minimum temperatures generated by the 'rand' function. These parameters can be changed at will.
// We also multiply these temperatures by 10 because the 'rand' function only returns integer values so afterwards we divide it by 10.
// EXAMPLE : rand = 57 /10 = 5.7 degrees

#define Temperature_Day_Upper_limit 90 
#define Temperature_Day_Lower_limit 30
#define Temperature_Night_Upper_limit 20
#define Temperature_Night_Lower_limit 30

/* Function declarations */

void Hello(void);
void Bye_Message(void);
void Read_Temperature(float[][Days], char[][Day_NameLength]);
void Calculate(float[][Days], int*, int*,int*,int*, int*, int*, int*, int*);
void Print(float[][Days], char[][Day_NameLength], int, int,int,int, int, int, int, int);
void Print_Line(int);

int main(void)
{
	/* Exercice 11.5

	Assignment:
	Write a program that reads the temperatures of a full week, finds
	the min and max temperatures and prints them together with all
	entered temperatures.
	print the temperatures as follows:

		   Mon  Tue  Wed  Thu  Fri  Sat  Sun
	Day    5.0  5.5  7.0  6.0  7.5  8.0  8.5
	Night -1.5 -0.5  0.0 -1.0  0.0  1.0  1.5 

	Print also min and max temperatures of day and night together with
	the day that temperature was measured:

	Min: Night: Mon = -1.5
		 Day:   Mon =  5.0
	Max: Night: Sun =  1.5
		 Day:   Sun =  8.5 

	The temperatures are stored in a 2D array with row 0 for the
	temperatures measured during the day and row 1 for the
	temperatures measured during the night. The names of the days are
	stored in a separate array (you cannot store numbers and text in the same array).

	Use 3 functions: Read, Print and Calculate. Pass the indexes of
	the min and max temperatures for day and night by reference!!!!

	*/

	printf("\n\t----\tDit is oefening 11.5 van 'Cprogrammingfundamentals2020' Pg164\t----\n\n\n\n");

	Hello();

	float Temperature[Number_of_Temperatures][Days];
	int min_Day = 0, MAX_Day = 0,min_Night = 0 ,MAX_Night = 0
		,min_DayWeek = 0,MAX_DayWeek = 0,min_NightWeek = 0,MAX_NightWeek = 0;
	char Day[Days][Day_NameLength];

	Read_Temperature(Temperature,Day);

	Calculate(Temperature, &min_Day, &MAX_Day, &min_Night, &MAX_Night, &min_DayWeek, &MAX_DayWeek, &min_NightWeek, &MAX_NightWeek);

	Print(Temperature, Day, min_Day, MAX_Day, min_Night, MAX_Night, min_DayWeek, MAX_DayWeek, min_NightWeek, MAX_NightWeek);

	Bye_Message();


	return 0;
}

/* Function definitions */

void Read_Temperature(float T[][Days],char D[][Day_NameLength])
{
	// Filling in day names into the day(D) matrix

	strcpy(D[0],"Mon");
	strcpy(D[1],"Tue");
	strcpy(D[2],"Wed");
	strcpy(D[3],"Thu");
	strcpy(D[4],"Fri");
	strcpy(D[5],"Sat");
	strcpy(D[6],"Sun");

	// Filling in all temperatures into the temperature(T) matrix

	char Answer;

	printf("\n Choose entry method. MANUAL(m) or AUTOMATIC(a) => "); // The user can choose whether he wants to fill in the temperatures manually or be automatically generated 
	scanf("%c%*c", &Answer);

	while (Answer != 'm' && Answer != 'a')
	{
		printf("\n\n\t ERROR \n\n Choose entry method. MANUAL(m) or AUTOMATIC(a) => ");
		scanf("%c%*c", &Answer);
	}

	if (Answer == 'm')
	{
		for (int i = 0; i < Number_of_Temperatures; i++)
		{
			for (int t = 0; t < Days; t++)
			{
				if (i == 0 && t == 0)
				{
					printf("\n\nEnter day temperatures : ");
				}
				
				if (i == 1 && t == 0)
				{
					printf("\n\nEnter night temperatures : ");
				}

				scanf("%f%*c",&T[i][t]);

			}
		}
	}
	else  // If answer is automatic(a) then random temperatures will be generated
	{
		srand(time(NULL));

		for (int i = 0; i < Number_of_Temperatures; i++)
		{

			for (int t = 0; t < Days; t++)
			{
				float m;
				if (i % 2 == 0) // If 'i' modulo 2 equals 0 we generate random temperatures for Daytime
				{
					if (rand() % 2 == 0) // If 'rand' modulo 2 equals 0 we generate random POSITIVE temperatures for Daytime
					{
						m = 1;

						T[i][t] = ((float)m * (float)(rand() % Temperature_Day_Upper_limit))/10;
					}
					else // If 'rand' modulo 2 equals 1 we generate random NEGATIVE temperatures for Daytime
					{
						m = -1;

						T[i][t] = ((float)m * (float)(rand() % Temperature_Day_Lower_limit))/10;
					}
				}
				else // If 'i' modulo 2 equals 1 we generate random temperatures for Night-time
				{
					if (rand() % 2 == 0) // If 'rand' modulo 2 equals 0 we generate random POSITIVE temperatures for Night-time
					{
						m = 1;

						T[i][t] = ((float)m * (float)(rand() % Temperature_Night_Upper_limit))/10;
					}
					else // If 'rand' modulo 2 equals 1 we generate random NEGATIVE temperatures for Night-time
					{
						m = -1;

						T[i][t] = ((float)m * (float)(rand() % Temperature_Night_Lower_limit))/10;
					}
				}



			}
		}
	}


}

void Calculate(float T[][Days], int * min_Day, int * MAX_Day, int * min_Night, int * MAX_Night, int * min_DayWeek, int * MAX_DayWeek, int * min_NightWeek, int * MAX_NightWeek) // REMEMBER : Pass the indexes of the min and max temperatures for day and night by reference.
{

	for (int t = 0; t < Number_of_Temperatures; t++)
	{

		for (int i = 0; i < Days; i++)
		{

			if (t % 2 == 0) // If 't' modulo 2 equals 0 we search for 'min' and 'MAX' by DAY
			{
				
				if (T[*min_DayWeek][*min_Day] > T[t][i]) // For each value of the table we compare two values at a time. After comparing which is the smallest value or biggest value we save their indexes and compare to the next value in line
				{
					*min_Day = i;
					*min_DayWeek = t;
				}

				if (T[*MAX_DayWeek][*MAX_Day] < T[t][i]) // If the value we are comparing our 'saved' value to is bigger then our 'saved' value the compared value becomes our 'saved' value
				{
					*MAX_Day = i;
					*MAX_DayWeek = t;
				}

			}
			else // If 't' modulo 2 equals 1 we search for 'min' and 'MAX' by NIGHT = 1
			{

				if (T[*min_NightWeek][*min_Night] > T[t][i])
				{
					*min_Night = i;
					*min_NightWeek = t;
				}

				if (T[*MAX_NightWeek][*MAX_Night] < T[t][i])
				{
					*MAX_Night = i;
					*MAX_NightWeek = t;
				}

			}

		}
	}

}

void Print(float T[][Days], char D[][Day_NameLength], int min_Day, int MAX_Day, int min_Night, int MAX_Night, int min_DayWeek, int MAX_DayWeek, int min_NightWeek, int MAX_NightWeek)
{
	// 1st Table = Week temperatures -----------------------------------
	
	/* Example :
	
	Week1 |  Mon  |  Tue  | Wed  |  Thu  |  Fri  |  Sat  |  Sun  |
	--------------------------------------------------------------
	Day   |  5.0  |  5.5  | 7.0  |  6.0  |  7.5  |  8.0  |  8.5  |
	Night | -1.5  | -0.5  | 0.0  | -1.0  |  0.0  |  1.0  |  1.5  | 
	--------------------------------------------------------------
	Week2 |  Mon  |  Tue  | Wed  |  Thu  |  Fri  |  Sat  |  Sun  |
	--------------------------------------------------------------
	Day   |  5.0  |  5.5  | 7.0  |  6.0  |  7.5  |  8.0  |  8.5  |
	Night | -1.5  | -0.5  | 0.0  | -1.0  |  0.0  |  1.0  |  1.5  |
	--------------------------------------------------------------
	...etc

	*/

	
	for (int w = 0; w < ceil(Number_of_Temperatures/2); w++)
	{

		printf("\nWeek%2d |", w + 1); // First we print the days of the week. The matix 'D' will provide us with it [0-6][0-4]
		for (int t = 0; t < Days; t++)
		{

			printf("  %s  |", D[t]);

		}

		Print_Line(64);

		for (int i = w * 2; i < w * 2 + 2; i++)
		{

			if (i % 2 == 0) // Secondly we print the word "Day" and then the first row [0][0-6] of the matrix 'T'
			{
				printf("\nDay    |");
			}
			else // At last we print the word "Night" and then the second row [1][0-6] of the matrix 'T'
			{
				printf("\nNight  |");
			}

			for (int m = 0; m < Days; m++)
			{

				printf("%5.1f  |", T[i][m]);

			}

		}

		Print_Line(64);
	}
	

	

	// 2nd Table = min and MAX temperatures ----------------------------

	/* Example
	
	Min: Night: Mon = -1.5
		 Day:   Mon =  5.0
	----------------------
	Max: Night: Sun =  1.5
		 Day:   Sun =  8.5
	
	*/

	printf("\n\n");

	printf("Min : \t Day    =>\t %s = %4.1f \n\t Night  =>\t %s = %4.1f",D[min_Day],T[min_DayWeek][min_Day], D[min_Night],T[min_NightWeek][min_Night]);

	Print_Line(40);

	printf("\nMax : \t Day   =>\t %s = %4.1f \n\t Night  =>\t %s = %4.1f", D[MAX_Day], T[MAX_DayWeek][MAX_Day], D[MAX_Night], T[MAX_NightWeek][MAX_Night]);
}

void Print_Line(int Number)
{
	printf("\n");
	for (int i = 0; i < Number; i++)
	{
		printf("-");
	}

}





void Hello(void)
{

	printf("\n\n");

	printf("\n\t      \x5F\x5F\x5F\x5F          \x5F\x5F\x5F\x5F           \x5F\x5F\x5F\x5F        \x5F\x5F\x5F\x5F        \x5F\x5F\x5F\x5F                         ");
	printf("\n\t     \x2F   \x2F\x5C        \x2F   \x2F\x5C         \x2F   \x2F\x5C      \x2F   \x2F\x5C      \x2F   \x2F\x5C                                       ");
	printf("\n\t    \x2F   \x2F\x3A\x2F       \x2F   \x2F\x3A\x3A\x5C       \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x3A\x5C                 ");
	printf("\n\t   \x2F   \x2F\x3A\x2F       \x2F   \x2F\x3A\x2F\x5C\x3A\x5C     \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x2F\x5C\x3A\x5C     ");
	printf("\n\t  \x2F   \x2F\x3A\x3A\x5C \x5F\x5F\x5F  \x2F   \x2F\x3A\x3A\x5C \x5C\x3A\x5C   \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x2F  \x5C\x3A\x5C    ");
	printf("\n\t \x2F\x5F\x5F\x5F\x2F\x3A\x2F\x5C\x3A\x5C  \x2F\x5C\x2F\x5F\x5F\x5F\x2F\x3A\x2F\x5C\x3A\x5C \x5C\x3A\x5C \x2F\x5F\x5F\x5F\x2F\x3A\x2F     \x2F\x5F\x5F\x5F\x2F\x3A\x2F     \x2F\x5F\x5F\x5F\x2F\x3A\x2F \x5C\x5F\x5F\x5C\x3A\x5C    ");
	printf("\n\t \x5C\x5F\x5F\x5F\x5C\x2F  \x5C\x3A\x5C\x2F\x3A\x2F\x5C   \x5C\x3A\x5C \x5C\x3A\x5C\x5F\x5C\x2F \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C \x2F  \x2F\x3A\x2F  ");
	printf("\n\t      \x5C\x5F\x5F\x5F\x5C\x3A\x3A\x2F  \x5C   \x5C\x3A\x5C \x5C\x3A\x5C    \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C  \x2F\x3A\x2F     ");
	printf("\n\t      \x2F   \x2F\x3A\x2F    \x5C   \x5C\x3A\x5C\x5F\x5C\x2F     \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C\x2F\x3A\x2F       ");
	printf("\n\t     \x2F\x5F\x5F\x5F\x2F\x3A\x2F      \x5C   \x5C\x3A\x5C        \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x3A\x2F                   ");
	printf("\n\t     \x5C\x5F\x5F\x5F\x5C\x2F        \x5C\x5F\x5F\x5F\x5C\x2F         \x5C\x5F\x5F\x5F\x5C\x2F      \x5C\x5F\x5F\x5F\x5C\x2F      \x5C\x5F\x5F\x5F\x5C\x2F   ");

	printf("\n\n\n");


}



void Bye_Message(void)
{

	printf("\n\n");

	printf("\n\t\t \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB");
	printf("\n\t\t \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDF\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB");
	printf("\n\t\t \xDB\xDB\xDB\xDB\xDB\xDB\xB2\xB2\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB");
	printf("\n\t\t \xDB\xDB\xDB\xDB\xDB\xDF\xB2\xDC\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB");
	printf("\n\t\t \xDB\xDB\xDB\xDB\xDB\xB2\xB2\xDF\xDF\xDF\xDF\xDF\xDB\xDB\xDB\xDF\xDF\xDB\xDB\xDB\xDB\xDB\xDF\xDF\xDB\xDB\xDB\xDF\xDF\xDF\xDF\xDF\xDB\xDB\xDB\xDB");
	printf("\n\t\t \xDB\xDB\xDB\xDB\xDB\xB2\xB2\xDC\xDB\xDB\xDC\xB2\xB2\xDB\xDB\xDB\xB2\xB2\xDB\xDB\xDB\xB2\xB2\xDB\xDB\xDB\xB2\xB2\xDB\xDB\xDB\xB2\xB2\xDB\xDB\xDB");
	printf("\n\t\t \xDB\xDB\xDB\xDB\xB2\xB2\xDB\xDB\xDB\xDB\xDB\xB2\xB2\xDB\xDB\xDB\xB2\xDC\xDB\xDB\xDB\xB2\xB2\xDB\xDB\xB2\xB2\xDF\xDF\xDF\xB2\xDC\xDB\xDB\xDB\xDB");
	printf("\n\t\t \xDB\xDB\xDB\xDB\xB2\xB2\xDB\xDB\xDB\xDB\xDF\xB2\xDB\xDB\xDB\xB2\xB2\xDB\xDB\xDB\xDF\xB2\xDB\xDB\xDB\xB2\xB2\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB");
	printf("\n\t\t \xDB\xDB\xDB\xDB\xB2\xB2\xDB\xDF\xDF\xB2\xDC\xDB\xDB\xDB\xDB\xDC\xB2\xDF\xDF\xDF\xB2\xDC\xDB\xDB\xDB\xDC\xB2\xDF\xDF\xDF\xB2\xDC\xDB\xDB\xDB\xDB");
	printf("\n\t\t \xDB\xDB\xDB\xDB\xDB\xDC\xDC\xDC\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xB2\xB2\xDB\xDB\xDB\xDB\xDB\xDB\xDC\xDC\xDB\xDB\xDB\xDB\xDB\xDB\xDB");
	printf("\n\t\t \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xB2\xDF\xDB\xDF\xB2\xDC\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB");
	printf("\n\t\t \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDC\xDC\xDC\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB");

	printf("\n\n\n");

}