/*

	C Fundamentals: Labo YT5883
	Exercices from "Cprogrammingfundamentals2020"

	Name: Celik
	Firstname:Ennis
	Class: 1EICT

*/


#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <time.h>
#include <math.h>
#define MAX 100
#define min 0

/* Function declarations */

void Hello(void);

int ReadSize(int,int);
void ReadArray(int[], int);
void PrintArray(int[], int);


int main(void)
{
	/* Exercice 7.8

	Assignment:
	Write a program with a main function and 3 extra functions.
	- In the main function an array of 100 integers is declared and the 3
	 extra functions are called.
	- The first function reads 1 integer in the interval [0, 100]. This 
	 integer represents the effective number of elements the array will
	 contain. This integer needs to be returned to the main program.
	- The second function reads the correct number of integers and stores
	them in the array. 
	- The third function prints the previously read integers.

	*/

	printf("\n\t----\tDit is oefening 7.8 van 'Cprogrammingfundamentals2020' Pg120\t----\n\n\n\n");

	Hello();

	int row[MAX];
	int size;
	

	size = ReadSize(min, MAX);

	ReadArray(row, size);

	printf("\n\n\t THE SIZE OF THE ARRAY IS => %d \n\t HERE IT IS :\n\n", size);

	PrintArray(row, size);

	return 0;
}




// The user decides the actual size of the array
int ReadSize(int Min, int Max)
{

	int S;

	do
	{
		printf("\n How large do you want the array to be ?(min: %d ; max: %d) : => ",min,MAX);
		scanf("%d%*c", &S);
	} while (S < min || S > MAX);
	
	return S;

}




// Filling the array with numbers generated by the user or the random generator
void ReadArray(int x[], int S)
{
	char Answer;

	// Asking the user if he/she wishes to enter all integers manually or not
	printf("\n\n Do you want to enter %d integers yourself? (Y/N) : ", S);

	scanf("%c%*c", &Answer);

	while (Answer != 'y' && Answer != 'n')
	{
		printf("\n Answer not correct. \n Please do you want to enter %d Numbers yourself? (Y/N) : ", S);
		scanf("%c%*c", &Answer);
	}

	// If the user's answer is positive (y) then we will ask the user to enter the integers
	// The user is not restricted to any integer limit unlike the random integer generator 
	if (Answer == 'y')
	{

		int Help_var;
		Help_var = 0;
		do
		{
			printf("\n Please enter %d numbers (%d numbers left) : =>",S ,S - Help_var);

			for (int i = 0; i < S; i++)
			{
				scanf("%d%*c", x[i]);

				Help_var++;
			}

		} while (x[S - 1] == NULL);

	}

	// If the user's answer is negative (n) then we will generate 100 random integers in the interval [1;1000] because we don't want to overdo
	printf("\n Then I will generate %d random numbers between [0 ; 1000]", S);

	if (Answer == 'n')
	{
		srand(time(NULL));
		int Help_var;

		for (int t = 0; t < S; t++)
		{
			Help_var = rand() % 1000 + 1;
			x[t] = Help_var;
		}

	}
	



}



// Printing the array in a matrix format
void PrintArray(int x[], int S)
{
	int i, m;
	m = 0;

	for (int n = 0; n < 5; n++)
	{
		i = 0;
		while (i < 20 && m < S)
		{
			printf("%4d |", x[i + n * (MAX / 5)]);

			i++;
			m++;
		}
			
		printf("\n");
	}
			

	

}








void Hello(void)
{
	printf("\n\n");

	printf("\n      \x5F\x5F\x5F\x5F          \x5F\x5F\x5F\x5F           \x5F\x5F\x5F\x5F        \x5F\x5F\x5F\x5F        \x5F\x5F\x5F\x5F                         ");
	printf("\n     \x2F   \x2F\x5C        \x2F   \x2F\x5C         \x2F   \x2F\x5C      \x2F   \x2F\x5C      \x2F   \x2F\x5C                                       ");
	printf("\n    \x2F   \x2F\x3A\x2F       \x2F   \x2F\x3A\x3A\x5C       \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x3A\x5C                 ");
	printf("\n   \x2F   \x2F\x3A\x2F       \x2F   \x2F\x3A\x2F\x5C\x3A\x5C     \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x2F\x5C\x3A\x5C     ");
	printf("\n  \x2F   \x2F\x3A\x3A\x5C \x5F\x5F\x5F  \x2F   \x2F\x3A\x3A\x5C \x5C\x3A\x5C   \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x2F  \x5C\x3A\x5C    ");
	printf("\n \x2F\x5F\x5F\x5F\x2F\x3A\x2F\x5C\x3A\x5C  \x2F\x5C\x2F\x5F\x5F\x5F\x2F\x3A\x2F\x5C\x3A\x5C \x5C\x3A\x5C \x2F\x5F\x5F\x5F\x2F\x3A\x2F     \x2F\x5F\x5F\x5F\x2F\x3A\x2F     \x2F\x5F\x5F\x5F\x2F\x3A\x2F \x5C\x5F\x5F\x5C\x3A\x5C    ");
	printf("\n \x5C\x5F\x5F\x5F\x5C\x2F  \x5C\x3A\x5C\x2F\x3A\x2F\x5C   \x5C\x3A\x5C \x5C\x3A\x5C\x5F\x5C\x2F \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C \x2F  \x2F\x3A\x2F  ");
	printf("\n      \x5C\x5F\x5F\x5F\x5C\x3A\x3A\x2F  \x5C   \x5C\x3A\x5C \x5C\x3A\x5C    \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C  \x2F\x3A\x2F     ");
	printf("\n      \x2F   \x2F\x3A\x2F    \x5C   \x5C\x3A\x5C\x5F\x5C\x2F     \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C\x2F\x3A\x2F       ");
	printf("\n     \x2F\x5F\x5F\x5F\x2F\x3A\x2F      \x5C   \x5C\x3A\x5C        \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x3A\x2F                   ");
	printf("\n     \x5C\x5F\x5F\x5F\x5C\x2F        \x5C\x5F\x5F\x5F\x5C\x2F         \x5C\x5F\x5F\x5F\x5C\x2F      \x5C\x5F\x5F\x5F\x5C\x2F      \x5C\x5F\x5F\x5F\x5C\x2F   ");

	printf("\n\n\n");


}