/*

	C Fundamentals: Labo YT5883
	Exercices from "Cprogrammingfundamentals2020"

	Name: Celik
	Firstname:Ennis
	Class: 1EICT

*/


#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <time.h>
#include <math.h>
#define MAX 100
#define min 0

/* Function declarations */

void Hello(void);


int ReadArray(int[]);
void PrintArray(int[], int);
double Mean_Calculator(int[], int);

int main(void)
{
	/* Exercice 7.10

	Assignment:
	Add an extra function to exercise 7.9 that calculates the mean value 
	of all entered integers and returns that mean value to the main function. 
	The mean must be printed in the main function.
	The header of this extra function could be like:

	*/

	printf("\n\t----\tDit is oefening 7.10 van 'Cprogrammingfundamentals2020' Pg121\t----\n\n\n\n");

	Hello();

	int row[MAX];
	int size;
	double Mean;


	size = ReadArray(row);

	Mean =  Mean_Calculator(row,size);

	printf("\n\n\t THE SIZE OF THE ARRAY IS => %d \n\t HERE IT IS :\n\n", size);


	PrintArray(row, size);

	printf("\n\n\t THE MEAN IS EQUAL TO : %.3f \n\n\n", Mean);



	return 0;



}



// Filling the array with numbers generated by the user
int ReadArray(int x[])
{
	char Answer;
	int S, Number;  // 'S' alias for "Size"
	S = 0;

	printf("\n Enter as many digits that you want. Finish with 999 if you're done : \n\n\t => ");
	scanf("%d%*c", &Number);

	// Start scanning for numbers
	while (Number != 999)
	{
		x[S] = Number;
		S++;
		scanf("%d%*c", &Number);
	}
	return S;

}


double Mean_Calculator(int x[], int S)
{

	double SUM;
	SUM = 0;

	for (int i = 0; i < S; i++)
	{
		SUM = SUM + x[i];
	}

	SUM = SUM / S;

	return SUM;

}



// Printing the array in a matrix format (kind of)
void PrintArray(int x[], int S)
{
	int i, m;
	m = 0;

	for (int n = 0; n < 5; n++)
	{
		i = 0;
		while (i < 20 && m < S)
		{
			printf("%5d |", x[i + n * (MAX / 5)]);

			i++;
			m++;
		}

		printf("\n");
	}




}








void Hello(void)
{
	printf("\n\n");

	printf("\n      \x5F\x5F\x5F\x5F          \x5F\x5F\x5F\x5F           \x5F\x5F\x5F\x5F        \x5F\x5F\x5F\x5F        \x5F\x5F\x5F\x5F                         ");
	printf("\n     \x2F   \x2F\x5C        \x2F   \x2F\x5C         \x2F   \x2F\x5C      \x2F   \x2F\x5C      \x2F   \x2F\x5C                                       ");
	printf("\n    \x2F   \x2F\x3A\x2F       \x2F   \x2F\x3A\x3A\x5C       \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x3A\x5C                 ");
	printf("\n   \x2F   \x2F\x3A\x2F       \x2F   \x2F\x3A\x2F\x5C\x3A\x5C     \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x2F\x5C\x3A\x5C     ");
	printf("\n  \x2F   \x2F\x3A\x3A\x5C \x5F\x5F\x5F  \x2F   \x2F\x3A\x3A\x5C \x5C\x3A\x5C   \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x2F     \x2F   \x2F\x3A\x2F  \x5C\x3A\x5C    ");
	printf("\n \x2F\x5F\x5F\x5F\x2F\x3A\x2F\x5C\x3A\x5C  \x2F\x5C\x2F\x5F\x5F\x5F\x2F\x3A\x2F\x5C\x3A\x5C \x5C\x3A\x5C \x2F\x5F\x5F\x5F\x2F\x3A\x2F     \x2F\x5F\x5F\x5F\x2F\x3A\x2F     \x2F\x5F\x5F\x5F\x2F\x3A\x2F \x5C\x5F\x5F\x5C\x3A\x5C    ");
	printf("\n \x5C\x5F\x5F\x5F\x5C\x2F  \x5C\x3A\x5C\x2F\x3A\x2F\x5C   \x5C\x3A\x5C \x5C\x3A\x5C\x5F\x5C\x2F \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C \x2F  \x2F\x3A\x2F  ");
	printf("\n      \x5C\x5F\x5F\x5F\x5C\x3A\x3A\x2F  \x5C   \x5C\x3A\x5C \x5C\x3A\x5C    \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C  \x2F\x3A\x2F     ");
	printf("\n      \x2F   \x2F\x3A\x2F    \x5C   \x5C\x3A\x5C\x5F\x5C\x2F     \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C\x2F\x3A\x2F       ");
	printf("\n     \x2F\x5F\x5F\x5F\x2F\x3A\x2F      \x5C   \x5C\x3A\x5C        \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x5C     \x5C   \x5C\x3A\x3A\x2F                   ");
	printf("\n     \x5C\x5F\x5F\x5F\x5C\x2F        \x5C\x5F\x5F\x5F\x5C\x2F         \x5C\x5F\x5F\x5F\x5C\x2F      \x5C\x5F\x5F\x5F\x5C\x2F      \x5C\x5F\x5F\x5F\x5C\x2F   ");

	printf("\n\n\n");


}